blank_issues_enabled: true
contact_links:
  - name: 📚 Documentation
    url: https://docs.rayners.dev/
    about: View comprehensive documentation and guides
  - name: 💬 GitHub Discussions
    url: https://github.com/rayners/fvtt-errors-and-echoes/discussions
    about: Ask questions and discuss with the community
  - name: 🔒 Security Issues
    url: https://github.com/rayners/fvtt-errors-and-echoes/security/advisories/new
    about: Report security vulnerabilities privately
