name: Release Please

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Release Please
        id: release
        uses: googleapis/release-please-action@v4

  build-and-upload:
    if: needs.release-please.outputs.release_created
    needs: release-please
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run validation
        run: npm run validate

      - name: Build module
        run: npm run build

      - name: Create module archive
        run: |
          cd dist
          zip -r ../fvtt-errors-and-echoes-${{ needs.release-please.outputs.tag_name }}.zip .
          cd ..

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.release-please.outputs.tag_name }}
          files: |
            fvtt-errors-and-echoes-${{ needs.release-please.outputs.tag_name }}.zip
            dist/module.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}