name: Release Module

on:
  release:
    types: [published]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and Release Module
        id: module_release
        uses: rayners/foundry-module-actions/release@v1
        with:
          node-version: '18'
          build-command: 'npm run build'
          working-directory: 'dist'
          module-files: 'module.json module.js styles/ templates/ languages/ examples/'
          zip-name: 'fvtt-errors-and-echoes.zip'

      # Foundry VTT Package Release submission commented out until package is registered
      # - name: Submit to Foundry VTT Package Release API
      #   uses: rayners/foundry-module-actions/foundry-release@v1
      #   with:
      #     package-id: 'errors-and-echoes'
      #     release-token: ${{ secrets.FOUNDRY_RELEASE_TOKEN }}
      #     version: ${{ steps.module_release.outputs.version }}
      #     manifest-url: 'https://github.com/${{ github.repository }}/releases/download/${{ github.event.release.tag_name }}/module.json'
      #     minimum-foundry-version: '12'
      #     verified-foundry-version: '13'