name: Trigger Documentation Update

on:
  release:
    types: [published]

jobs:
  trigger-docs-update:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger documentation update
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: rayners/foundry-docs
          event-type: update-docs
          client-payload: '{"module_name": "errors-and-echoes"}'
